# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WaterQual
                                 A QGIS plugin
 This plugin is about the water quality of lakes using Sentinel 2 images
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-01-02
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Ilias Machairas, Ashish Kuruvila
        email                : iliasmachairas@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import json
from datetime import datetime, timedelta

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QUrl
from qgis.PyQt.QtGui import QIcon, QDesktopServices
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import (
    Qgis, QgsMessageLog, QgsCoordinateReferenceSystem, QgsCoordinateTransform,
    QgsGeometry, QgsProject,
)
from qgis.gui import QgsMapToolPan

from .WaterQual_dialog import WaterQualDialog
from .extent_tool import ExtentDrawingTool
from .worker import AnalysisWorker


class WaterQual:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.iface      = iface
        self.plugin_dir = os.path.dirname(__file__)

        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir, 'i18n',
            'WaterQual_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions     = []
        self.menu        = self.tr(u'&WaterQual')
        self.first_start = None
        self.worker      = None
        self.dlg         = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        return QCoreApplication.translate('WaterQual', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):

        icon   = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        self.add_action(
            f'{self.plugin_dir}/lake.png',
            text=self.tr(u'WaterQual — Sentinel-2 Water Analysis'),
            callback=self.run,
            parent=self.iface.mainWindow())
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&WaterQual'), action)
            self.iface.removeToolBarIcon(action)

    # ── Signal handlers ───────────────────────────────────────────────────────

    def _browse_output(self):
        folder = QFileDialog.getExistingDirectory(
            self.dlg, "Select output directory",
            self.dlg.lineEdit_output.text() or os.path.expanduser("~"),
        )
        if folder:
            self.dlg.lineEdit_output.setText(folder)

    def _select_all_clouds(self):
        for cb in (self.dlg.cb_cloud_shadows, self.dlg.cb_cloud_low,
                   self.dlg.cb_cloud_med, self.dlg.cb_cloud_high, self.dlg.cb_cirrus):
            cb.setChecked(True)

    def _unselect_all_clouds(self):
        for cb in (self.dlg.cb_cloud_shadows, self.dlg.cb_cloud_low,
                   self.dlg.cb_cloud_med, self.dlg.cb_cloud_high, self.dlg.cb_cirrus):
            cb.setChecked(False)

    def _start_draw_tool(self):
        """Minimise dialog and activate the rubber-band drawing tool."""
        self.dlg.setWindowState(Qt.WindowState.WindowMinimized)
        tool = ExtentDrawingTool(self.iface.mapCanvas(), self._handle_extent)
        self.iface.mapCanvas().setMapTool(tool)
        self.dlg.set_status("Draw a rectangle on the map…")

    def _handle_extent(self, xmin, ymin, xmax, ymax):
        """Callback from ExtentDrawingTool — fills coordinate fields."""
        self.dlg.set_aoi_from_extent(xmin, ymin, xmax, ymax)
        self.dlg.setWindowState(Qt.WindowState.WindowNoState)
        self.dlg.raise_()
        self.dlg.activateWindow()
        self.dlg.set_status(
            f"AOI: {xmin:.4f}, {ymin:.4f}  →  {xmax:.4f}, {ymax:.4f}")
        self.iface.mapCanvas().setMapTool(QgsMapToolPan(self.iface.mapCanvas()))

    def _show_help(self):
        """Open the online documentation (usage guide) in the system's default browser."""
        QDesktopServices.openUrl(
            QUrl("https://waterqual.readthedocs.io/en/latest/usage.html"))

    # ── Analysis logic ────────────────────────────────────────────────────────

    def _aoi_geojson_from_layer(self, layer):
        """Build an EPSG:4326 GeoJSON Feature covering every feature in `layer`,
        reprojected and unioned into a single (multi)polygon geometry."""
        if layer.featureCount() == 0:
            raise ValueError(f"Layer '{layer.name()}' has no features.")

        wgs84     = QgsCoordinateReferenceSystem("EPSG:4326")
        transform = QgsCoordinateTransform(layer.crs(), wgs84, QgsProject.instance())

        geometries = []
        for feature in layer.getFeatures():
            geom = feature.geometry()
            if geom is None or geom.isEmpty():
                continue
            geom = QgsGeometry(geom)
            geom.transform(transform)
            geometries.append(geom)

        if not geometries:
            raise ValueError(f"Layer '{layer.name()}' has no valid geometries.")

        union = QgsGeometry.unaryUnion(geometries)
        if union.isEmpty():
            raise ValueError(f"Could not combine the geometries in '{layer.name()}'.")

        return {
            "type": "Feature",
            "properties": {"name": layer.name()},
            "geometry": json.loads(union.asJson()),
        }

    def _run_analysis(self):
        d = self.dlg

        # Validate AOI
        points_list = None
        aoi_geojson = None
        aoi_bounds_msg = ""

        if d.get_aoi_source() == "draw":
            try:
                xmin, ymin, xmax, ymax = d.get_aoi_coords()
            except ValueError as e:
                self.iface.messageBar().pushMessage(
                    "Input Error", str(e), level=Qgis.MessageLevel.Critical, duration=5)
                return
            points_list = [
                [xmin, ymax], [xmax, ymax], [xmax, ymin], [xmin, ymin],
            ]
            aoi_bounds_msg = f"AOI (drawn) ({xmin:.4f},{ymin:.4f})→({xmax:.4f},{ymax:.4f})"
        else:
            layer = d.get_aoi_layer()
            if layer is None:
                self.iface.messageBar().pushMessage(
                    "Input Error", "Please select a polygon layer.",
                    level=Qgis.MessageLevel.Critical, duration=5)
                return
            try:
                aoi_geojson = self._aoi_geojson_from_layer(layer)
            except ValueError as e:
                self.iface.messageBar().pushMessage(
                    "Input Error", str(e), level=Qgis.MessageLevel.Critical, duration=5)
                return
            aoi_bounds_msg = f"AOI (layer) '{layer.name()}'"

        output_dir = d.get_output_dir()
        if not output_dir:
            self.iface.messageBar().pushMessage(
                "Input Error", "Please select an output directory.",
                level=Qgis.MessageLevel.Critical, duration=5)
            return

        selected_date = d.get_selected_date()
        extra_days    = d.get_extra_days()
        dt            = datetime.strptime(selected_date, "%Y-%m-%d")
        date_str      = (
            f"{(dt - timedelta(days=extra_days)).strftime('%Y-%m-%d')}/"
            f"{(dt + timedelta(days=extra_days)).strftime('%Y-%m-%d')}"
        )

        params = {
            "points_list":         points_list,
            "aoi_geojson":         aoi_geojson,
            "date_str":            date_str,
            "algorithm":           d.get_algorithm(),
            "restrict_to_water":   d.get_restrict_water(),
            "also_save_raw":       d.get_also_save_raw(),
            "max_cloud_tile":      d.get_max_cloud_tile(),
            "max_cloud_tolerance": d.get_max_cloud_tol(),
            "excluded_flags":      d.get_excluded_flags(),
            "output_directory":    output_dir,
            "create_report":       d.cb_report.isChecked(),
        }

        QgsMessageLog.logMessage(
            f"Run started — {date_str} | {aoi_bounds_msg}", "WaterQual")

        self.worker = AnalysisWorker(params)
        self.worker.progress.connect(d.set_progress)
        self.worker.message.connect(d.set_status)
        self.worker.finished.connect(self._on_finished)
        self.worker.error.connect(self._on_error)

        d.set_running(True)
        d.set_progress(0)
        d.set_status("Starting…")
        self.worker.start()

    def _on_finished(self, result: dict):
        self.dlg.set_running(False)
        status      = result.get("status", "unknown")
        aoi_warning = result.get("aoi_warning")

        if status == "analyzed":
            out    = result.get("output_path", "")
            raw    = result.get("raw_path")
            stats  = result.get("index_stats", {})
            algo   = result.get("algorithm", "")
            mean   = stats.get("mean")
            classification = stats.get("classification", "")
            msg = f"{algo} mean {mean:.3f} — {classification}" if mean is not None else "Done"
            self.dlg.set_status(msg)
            summary = f"{os.path.basename(out)}" + (f" (+ {os.path.basename(raw)})" if raw else "")
            self.iface.messageBar().pushMessage(
                "Water Quality Analysis Complete", f"{msg} — saved {summary}",
                level=Qgis.MessageLevel.Success, duration=8)
            QgsMessageLog.logMessage(f"Output: {out}" + (f" | Raw: {raw}" if raw else ""),
                                      "WaterQual")
            if self.dlg.cb_open_output.isChecked() and os.path.isdir(os.path.dirname(out)):
                # Opens the folder via the OS's file-association handler (Windows
                # ShellExecute); no shell is invoked and no string is parsed as a
                # command, so shell injection doesn't apply here.
                os.startfile(os.path.dirname(out))  # nosec B606

        elif status == "skipped":
            msg = "Skipped — cloud cover exceeded tolerance or no water pixels. See report."
            self.dlg.set_status(msg)
            self.iface.messageBar().pushMessage(
                "Skipped", msg, level=Qgis.MessageLevel.Warning, duration=6)
        else:
            self.dlg.set_status(f"Finished with status: {status}")

        if aoi_warning:
            self.iface.messageBar().pushMessage(
                "Incomplete AOI coverage", aoi_warning, level=Qgis.MessageLevel.Warning, duration=15)
            QgsMessageLog.logMessage(aoi_warning, "WaterQual", Qgis.MessageLevel.Warning)

    def _on_error(self, error_msg: str):
        self.dlg.set_running(False)
        self.dlg.set_progress(0)
        self.dlg.set_status("Error — see QGIS log panel for details.")
        self.iface.messageBar().pushMessage(
            "Error", error_msg.splitlines()[0], level=Qgis.MessageLevel.Critical, duration=10)
        QgsMessageLog.logMessage(error_msg, "WaterQual", Qgis.MessageLevel.Critical)

    # ── Entry point ───────────────────────────────────────────────────────────

    def run(self):
        """Run method that performs all the real work."""
        if self.first_start:
            self.first_start = False
            self.dlg = WaterQualDialog()

            self.dlg.toolButton.clicked.connect(self._browse_output)
            self.dlg.btn_select_all.clicked.connect(self._select_all_clouds)
            self.dlg.btn_unselect_all.clicked.connect(self._unselect_all_clouds)
            self.dlg.btn_draw_area.clicked.connect(self._start_draw_tool)
            self.dlg.btn_run.clicked.connect(self._run_analysis)
            self.dlg.btn_close.clicked.connect(self.dlg.close)
            self.dlg.btn_help.clicked.connect(self._show_help)

        if self.dlg.isVisible():
            self.dlg.raise_()
            self.dlg.activateWindow()
            return

        self.dlg.show()
