# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Lake_Analyzer
                                 A QGIS plugin
 This plugin is about the water quality of lakes using Sentinel 2 images
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-02
        copyright            : (C) 2026 by Ilias Machairas, Ashish Kuruvila
        email                : iliasmachairas@outlook.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Lake_Analyzer class from file Lake_Analyzer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Lake_Analyzer import Lake_Analyzer
    return Lake_Analyzer(iface)
