# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Lake_AnalyzerDialog
                                 A QGIS plugin
 This plugin is about the water quality of lakes using Sentinel 2 images
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-02
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Ilias Machairas, Ashish Kuruvila
        email                : iliasmachairas@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtWidgets import QButtonGroup
from qgis.core import QgsProject, QgsWkbTypes, QgsMapLayerType

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Lake_Analyzer_dialog_base.ui'))

# Widgets shown only in "Draw on map" AOI mode
_DRAW_WIDGETS = (
    "btn_draw_area", "label_top", "lineEdit_top", "label_left", "lineEdit_left",
    "label_right", "lineEdit_right", "label_bottom", "lineEdit_bottom",
)
# Widgets shown only in "From layer" AOI mode
_LAYER_WIDGETS = ("comboBox_aoi_layer", "label_aoi_layer_hint")

_ADVANCED_COLLAPSED_TEXT = "▸ Advanced masking options"
_ADVANCED_EXPANDED_TEXT  = "◂ Advanced masking options"


class Lake_AnalyzerDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(Lake_AnalyzerDialog, self).__init__(parent)
        self.setupUi(self)

        # Keep each radio-button row exclusive with the others but separate
        # from the rest — all radios share the same QDialog parent, so Qt
        # would otherwise treat them all as one exclusive group.
        self.algoGroup = QButtonGroup(self)
        self.algoGroup.addButton(self.radioBtn_algo_ndci, 0)
        self.algoGroup.addButton(self.radioBtn_algo_ndti, 1)
        self.algoGroup.addButton(self.radioBtn_algo_oc3, 2)
        self.algoGroup.addButton(self.radioBtn_algo_gilerson, 3)

        self.aoiGroup = QButtonGroup(self)
        self.aoiGroup.addButton(self.radioBtn_aoi_draw, 0)
        self.aoiGroup.addButton(self.radioBtn_aoi_layer, 1)
        self.radioBtn_aoi_draw.toggled.connect(self._update_aoi_mode)
        self._update_aoi_mode()

        # The advanced panel sits to the right of the dialog's collapsed
        # width and expands the dialog sideways rather than pushing any
        # other widget around — nothing below it ever needs to move. A
        # plain QPushButton + setVisible()/setFixedWidth() is used instead
        # of a custom collapsible-groupbox widget, so the click behavior
        # doesn't depend on that widget's own (unreliable) toggle.
        self._collapsed_width = self.width()
        self._expanded_width  = (
            self.groupBox_advanced.x() + self.groupBox_advanced.width() + 20)
        self.btn_toggle_advanced.setCheckable(True)
        self.btn_toggle_advanced.toggled.connect(self._toggle_advanced)
        self._toggle_advanced(False)

        self.calendarWidget.selectionChanged.connect(self._update_selected_date_label)
        self._update_selected_date_label()

    # ── Advanced panel ───────────────────────────────────────────────────────

    def _toggle_advanced(self, expanded):
        self.groupBox_advanced.setVisible(expanded)
        self.btn_toggle_advanced.setText(
            _ADVANCED_EXPANDED_TEXT if expanded else _ADVANCED_COLLAPSED_TEXT)
        self.setFixedWidth(self._expanded_width if expanded else self._collapsed_width)

    # ── AOI mode ──────────────────────────────────────────────────────────────

    def _update_aoi_mode(self):
        draw_mode = self.radioBtn_aoi_draw.isChecked()
        for name in _DRAW_WIDGETS:
            getattr(self, name).setVisible(draw_mode)
        for name in _LAYER_WIDGETS:
            getattr(self, name).setVisible(not draw_mode)
        if not draw_mode:
            self._populate_layer_combo()

    def _populate_layer_combo(self):
        """Refill the layer combo with the project's polygon vector layers."""
        current_id = self.comboBox_aoi_layer.currentData()

        self.comboBox_aoi_layer.blockSignals(True)
        self.comboBox_aoi_layer.clear()
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() != QgsMapLayerType.VectorLayer:
                continue
            if layer.geometryType() != QgsWkbTypes.GeometryType.PolygonGeometry:
                continue
            self.comboBox_aoi_layer.addItem(layer.name(), layer.id())

        if current_id is not None:
            idx = self.comboBox_aoi_layer.findData(current_id)
            if idx >= 0:
                self.comboBox_aoi_layer.setCurrentIndex(idx)
        self.comboBox_aoi_layer.blockSignals(False)

    # ── Date label ────────────────────────────────────────────────────────────

    def _update_selected_date_label(self):
        date_str = self.calendarWidget.selectedDate().toString("yyyy-MM-dd")
        self.label_selectedDate.setText(f"Selected: {date_str}")

    # ── Typed getters ─────────────────────────────────────────────────────────

    def get_algorithm(self):
        if self.radioBtn_algo_ndti.isChecked():
            return "ndti"
        if self.radioBtn_algo_oc3.isChecked():
            return "oc3"
        if self.radioBtn_algo_gilerson.isChecked():
            return "gilerson"
        return "ndci"

    def get_also_save_raw(self):
        return self.cb_also_raw.isChecked()

    def get_restrict_water(self):
        return self.cb_restrict_water.isChecked()

    def get_excluded_flags(self):
        mapping = {
            self.cb_cloud_shadows: "Cloud shadows",
            self.cb_cloud_low:     "Clouds low probability",
            self.cb_cloud_med:     "Cloud medium probability",
            self.cb_cloud_high:    "Cloud high probability",
            self.cb_cirrus:        "Thin cirrus",
        }
        return [name for cb, name in mapping.items() if cb.isChecked()]

    def get_aoi_source(self):
        return "draw" if self.radioBtn_aoi_draw.isChecked() else "layer"

    def get_aoi_coords(self):
        """Return (xmin, ymin, xmax, ymax) as floats, raise ValueError if invalid."""
        try:
            top    = float(self.lineEdit_top.text())
            bottom = float(self.lineEdit_bottom.text())
            left   = float(self.lineEdit_left.text())
            right  = float(self.lineEdit_right.text())
        except ValueError:
            raise ValueError("AOI coordinates must be valid decimal numbers.")
        if left >= right or bottom >= top:
            raise ValueError("Invalid AOI: left < right and bottom < top required.")
        return left, bottom, right, top  # xmin, ymin, xmax, ymax

    def get_aoi_layer(self):
        """Return the QgsVectorLayer selected in the 'From layer' combo, or None."""
        layer_id = self.comboBox_aoi_layer.currentData()
        if layer_id is None:
            return None
        return QgsProject.instance().mapLayer(layer_id)

    def get_extra_days(self):
        return self.spinBox_extraDays.value()

    def get_max_cloud_tile(self):
        try:
            return int(self.lineEdit_maxCloudTile.text())
        except ValueError:
            return 100

    def get_max_cloud_tol(self):
        try:
            return int(self.lineEdit_maxCloudTol.text())
        except ValueError:
            return 20

    def get_selected_date(self):
        return self.calendarWidget.selectedDate().toString("yyyy-MM-dd")

    def get_output_dir(self):
        return self.lineEdit_output.text().strip()

    # ── UI helpers ────────────────────────────────────────────────────────────

    def set_aoi_from_extent(self, xmin, ymin, xmax, ymax):
        self.lineEdit_left.setText(f"{xmin:.6f}")
        self.lineEdit_right.setText(f"{xmax:.6f}")
        self.lineEdit_bottom.setText(f"{ymin:.6f}")
        self.lineEdit_top.setText(f"{ymax:.6f}")

    def set_status(self, message):
        self.label_status.setText(message)

    def set_progress(self, value):
        self.progressBar.setValue(value)

    def set_running(self, running: bool):
        self.btn_run.setEnabled(not running)
        self.btn_close.setEnabled(not running)
